各実装内容
shishimaru7/Team2DGame pull request #29
Opened 2021-02-03 13:23 UTC by shishimaru7

・敵の出現Part2
・ステージ2地面の当たり判定
・ギミック2種類（出現場所未定）
・ライフの増減（※内容相談）
・ボムの増減（OK）
・変化弾の変化（OK）

2021-02-03 13:34 UTC, shishimaru7 commented
PlayerControllerがConflict（左クリックで発動）しましたがめぐりやさんの処理は残しておきました。

2021-02-04 14:56 UTC, megu-riya approved these changes
動作上問題ありそうなとこと、ビルドが通らないとこを指摘させてもらいました。
確認お願いします

2021-02-04 14:56 UTC, megu-riya commented on Assets/Script/Player/PlayerController.cs
> +
全角混ざってます

2021-02-04 14:56 UTC, megu-riya commented on Assets/Script/Player/PlayerController.cs
> +            PlayerInfoManager.Instance.BombMng.IsBombEmpty();
PlayerInfoManager.Instance.BombMng.IsBombEmpty();　関数は空かどうかを返す関数なので、このタイミングで呼びだす必要はないと思います

2021-02-04 14:56 UTC, megu-riya commented on Assets/Script/Player/PlayerController.cs
> +
isbomb 変数が宣言されていないです

2021-02-04 14:56 UTC, megu-riya commented on Assets/Script/Player/PlayerController.cs
> +                GameMainManager.Instance.GameOver();
GameOverをここで呼ぶ理由は何故でしょうか？
LifeMng内のLifeが 0になったら、自動でGameOverが呼び出されるので、プレイヤー側が呼び出す必要はありま

2021-02-04 14:56 UTC, megu-riya commented on Assets/Script/Player/PlayerController.cs
> +                GameMainManager.Instance.GameOver();
GameOverをここで呼ぶ理由は何故でしょうか？
LifeMng内のLifeが 0になったら、自動でGameOverが呼び出されるので、プレイヤー側が呼び出す必要はありません

2021-02-04 14:56 UTC, megu-riya commented on Assets/Script/Player/PlayerController.cs
> +       ｛
全角混ざってます

2021-02-04 15:25 UTC, megu-riya commented on Assets/Script/Player/PlayerController.cs
> +                GameMainManager.Instance.GameOver();
すみません、ここはわざとっぽいので、この指摘は取り下げます

2021-02-04 15:25 UTC, megu-riya commented on Assets/Script/Player/PlayerController.cs
> +                GameMainManager.Instance.GameOver();
すみません、ここもわざとっぽいので、この指摘は取り下げます

2021-02-06 07:33 UTC, megu-riya requested changes

2021-02-06 07:33 UTC, megu-riya commented on Assets/Script/Player/PlayerController.cs
> +        if (Input.GetMouseButtonDown(1) && waitTime <= chargeTime)
数のチェックしていないので、無限に特殊弾が打てそう

2021-02-06 07:33 UTC, megu-riya commented on Assets/Script/Player/PlayerController.cs
> +        if ((Input.GetKey(KeyCode.Joystick1Button1) || Input.GetMouseButtonDown(1)) && waitTime <= chargeTime)
数のチェックしていないので、無限に特殊弾が打てそう。
同じ処理が続いているので、どちらか削除

2021-02-06 07:33 UTC, megu-riya commented on Assets/Script/Player/PlayerController.cs
> +        if (Input.GetMouseButtonDown(1) && waitTime <= chargeTime)
if (Input.GetMouseButtonDown(1) && ( waitTime <= chargeTime ) && PlayerInfoManager.Instance.BombMng.IsBombEmpty() )

2021-02-06 07:38 UTC, megu-riya approved these changes

2021-02-06 07:38 UTC, merged