Stage3のギミックの修正
shishimaru7/Team2DGame pull request #45
Opened 2021-02-26 05:41 UTC by shishimaru7

・惑星の大きさ大中小とランダムで出現

2021-02-27 00:29 UTC, megu-riya requested changes
動作上は問題ありませんが、こういう感じの処理は積み重なると重たくなるので今のうちから気にかけるようにして欲しいです。

2021-02-27 00:29 UTC, megu-riya commented on Assets/Script/Gimmick/Gimmick_2.cs
> +            }
やりたいことはわからなくもないですが、、、
この処理に関してはfor分で回すのは無駄な処理が多くなるので、あまり良くないと思います。
サイズをあらかじめテーブルで定義しておいて、ランダム関数でindexを取得して、テーブルから設定するのがいいと思います

2021-03-01 01:12 UTC, megu-riya approved these changes
修正ありがとうございます。
コンフリクトしているので、解消したらマージお願いします

2021-03-01 03:01 UTC, shishimaru7 commented
Conflict解消しました。
デバッグ機能追加時にコードが変わっていたんですね。
気が付かずに修正してました。
Devの方でB⇒Aにコメント修正するべきでしたね。

2021-03-01 03:01 UTC, merged